#!/usr/bin/env bash

# If any command inside script returns error, exit and return that error
set -e

# Build backward-compatible version
python build.py

# Autoformat
autoflake --remove-all-unused-imports --remove-unused-variables --expand-star-imports --ignore-init-module-imports --remove-duplicate-keys -r -i .
isort -y
black -l 100 .

# Run unit tests (3.5)
source ~/miniconda3/etc/profile.d/conda.sh
conda activate py35

cp ../conftest.py .
cp -r ../unit_test .
pytest -vv unit_test
rm -r unit_test
rm conftest.py

conda deactivate

# Upload to PyPI
# rm -r dist/
# cp ../README.md .
# python setup.py sdist bdist_wheel
# twine upload dist/*
# rm README.md