#!/usr/bin/env bash

echo "Running pre-push hook"

rm coverage.xml
codecov --token="84d5db20-8416-49b1-81b2-c5fe2f008210"

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Pre-push must pass before pushing!"
 exit 1
fi
