name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
        pytorch-version: ["2.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install --system pytest pytest-cov
        uv pip install --system torch==${{ matrix.pytorch-version }} torchvision transformers
    - name: mypy
      if: ${{ matrix.pytorch-version == '2.11' }}
      run: |
        uv pip install --system mypy==1.9.0
        mypy --install-types --non-interactive .
    - name: pytest
      if: ${{ matrix.pytorch-version == '2.11' }}
      run: |
        pytest --cov=torchinfo --cov-report= --durations=0
    - name: codecov
      uses: codecov/codecov-action@v1
